version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env               # copy .env.example → .env and fill
    ports:
      - "8000:8000"
    restart: unless-stopped