version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env               # copy .env.example → .env and fill
    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - ./app:/app/app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 0627antaechan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json